server:
  port: 8080

env: "debug"

database:
  host: localhost
  port: 5432
  user: postgres
  password: your_database_password
  name: your_database_name
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0


jwt:
  secret: "your_jwt_secret_key"
  expires_in_minute: 1440
  token_ttl_minute: 1440
  refresh_expires_in_days: 7
kafka:
  brokers: ["localhost:9092"]

supabase:
  s3:
    endpoint: "https://your-project-ref.supabase.co/storage/v1/s3"
    region: "us-east-1"
    access_key_id: "your_supabase_access_key_id"
    secret_access_key: "your_supabase_secret_access_key"
    bucket: "your_bucket_name"
