server:
  port: 8080

env: "debug"

database:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  name: pentacore
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0


jwt:
  secret: "supersecretkey"
  expires_in_minute: 15
  refresh_expires_in_days: 7